// Datos fallback en memoria para cuando PostgreSQL está en reposo o inaccesible.
// Mantiene paridad 1:1 con server/src/seed.ts.

export interface FallbackOrg {
  slug: string
  name: string
  url: string | null
  city: string | null
  projects: { slug: string, title: string, year: number }[]
  experiences: { slug: string, role: string, startedAt: string, endedAt: string | null }[]
}

export const fallbackOrgs: Record<string, FallbackOrg> = {
  'la-rucula-gastrobar': {
    slug: 'la-rucula-gastrobar',
    name: 'La Rúcula Gastrobar',
    url: 'https://laruculagastrobar.es/',
    city: 'Chiclana de la Frontera, ES',
    projects: [{ slug: 'la-rucula', title: 'La Rúcula Gastrobar', year: 2026 }],
    experiences: [{ slug: 'la-rucula', role: 'Freelance · diseño y desarrollo', startedAt: '2026-03-17', endedAt: '2026-07-20' }],
  },
  'arg-piscinas': {
    slug: 'arg-piscinas',
    name: 'ARG Piscinas',
    url: 'https://www.argpiscinas.es/',
    city: 'Andalucía, ES',
    projects: [{ slug: 'argpiscinas', title: 'ARG Piscinas', year: 2026 }],
    experiences: [{ slug: 'arg-piscinas', role: 'Freelance · front y back a medida', startedAt: '2026-01-28', endedAt: '2026-07-20' }],
  },
  'escuela-da-vinci': {
    slug: 'escuela-da-vinci',
    name: 'Escuela Da Vinci',
    url: 'https://www.davinci.edu.ar/',
    city: 'Buenos Aires, AR',
    projects: [{ slug: 'ynara', title: 'Ynara', year: 2026 }],
    experiences: [
      { slug: 'ynara', role: 'Tesis en equipo · contribuidor principal', startedAt: '2026-05-18', endedAt: '2026-06-28' },
      { slug: 'escuela-da-vinci', role: 'Estudiante · Diseño y Desarrollo Web', startedAt: '2024-03-01', endedAt: null },
    ],
  },
  'cet-30': {
    slug: 'cet-30',
    name: 'CET N.º 30',
    url: null,
    city: 'Río Negro, AR',
    projects: [],
    experiences: [{ slug: 'cet-30', role: 'Técnico en Programación', startedAt: '2017-03-01', endedAt: '2023-12-01' }],
  },
}

export const fallbackExperience = [
  {
    id: 1,
    slug: 'ynara',
    role: 'Tesis en equipo · contribuidor principal',
    startedAt: '2026-05-18',
    endedAt: '2026-06-28',
    summary: '382 commits en seis semanas sobre Ynara, la tesis: asistente de IA on-prem con FastAPI, Next.js, Expo y Postgres con pgvector. Preaprobada; falta la defensa.',
    story: 'Tesis final en Escuela Da Vinci: desarrollo de un asistente de inteligencia artificial on-premise con FastAPI, Next.js, Expo y PostgreSQL con extensión pgvector. 382 commits liderando la arquitectura del backend, pipelines de embeddings vectoriales y la interfaz web.',
    org: { slug: 'escuela-da-vinci', name: 'Escuela Da Vinci', city: 'Buenos Aires, AR' },
    techs: [
      { slug: 'fastapi', name: 'FastAPI' },
      { slug: 'next', name: 'Next.js' },
      { slug: 'postgresql', name: 'PostgreSQL' },
      { slug: 'python', name: 'Python' },
      { slug: 'typescript', name: 'TypeScript' },
    ],
  },
  {
    id: 2,
    slug: 'la-rucula',
    role: 'Freelance · diseño y desarrollo',
    startedAt: '2026-03-17',
    endedAt: '2026-07-20',
    summary: 'Sitio editorial menu-first con panel de gestión propio. En producción.',
    story: 'De un PDF escaneado a una web menu-first optimizada para comensales en mesa mediante QR. Integración con panel de gestión propio y fallback offline local: si la API externa entra en reposo, el menú sigue disponible sin degradación.',
    org: { slug: 'la-rucula-gastrobar', name: 'La Rúcula Gastrobar', city: 'Chiclana de la Frontera, ES' },
    techs: [
      { slug: 'gsap', name: 'GSAP' },
      { slug: 'lenis', name: 'Lenis' },
      { slug: 'tailwind', name: 'Tailwind CSS' },
      { slug: 'vue', name: 'Vue 3' },
    ],
  },
  {
    id: 3,
    slug: 'arg-piscinas',
    role: 'Freelance · front y back a medida',
    startedAt: '2026-01-28',
    endedAt: '2026-07-20',
    summary: 'Web corporativa en tres idiomas con panel de gestión y blog. En producción.',
    story: 'Construcción integral de catálogo corporativo multi-idioma (ES/EN/DE). Implementación de panel autoadministrable para que el cliente cargue obras sin tocar código, tipado de punta a punta con Prisma y optimización de assets pesados para carga instantánea en conexiones móviles.',
    org: { slug: 'arg-piscinas', name: 'ARG Piscinas', city: 'Andalucía, ES' },
    techs: [
      { slug: 'gsap', name: 'GSAP' },
      { slug: 'node', name: 'Node.js' },
      { slug: 'prisma', name: 'Prisma' },
      { slug: 'tailwind', name: 'Tailwind CSS' },
      { slug: 'vue', name: 'Vue 3' },
    ],
  },
  {
    id: 4,
    slug: 'escuela-da-vinci',
    role: 'Estudiante · Diseño y Desarrollo Web',
    startedAt: '2024-03-01',
    endedAt: null,
    summary: 'Carrera en curso, promoción 2026. UI/UX, dirección visual, front moderno, back, bases de datos y arquitectura. Tesis preaprobada: Ynara.',
    story: 'Formación intensiva de 3 años en Diseño y Desarrollo Web: principios de UI/UX, tipografía, dirección visual, arquitecturas de software modernas, patrones de concurrencia y bases de datos relacionales y no-relacionales.',
    org: { slug: 'escuela-da-vinci', name: 'Escuela Da Vinci', city: 'Buenos Aires, AR' },
    techs: [
      { slug: 'fastapi', name: 'FastAPI' },
      { slug: 'laravel', name: 'Laravel' },
      { slug: 'mongodb', name: 'MongoDB' },
      { slug: 'php', name: 'PHP' },
      { slug: 'postgresql', name: 'PostgreSQL' },
      { slug: 'react', name: 'React' },
      { slug: 'vue', name: 'Vue 3' },
    ],
  },
  {
    id: 5,
    slug: 'freelance',
    role: 'Freelance · diseño y desarrollo web',
    startedAt: '2023-01-01',
    endedAt: null,
    summary: 'Alrededor de diez proyectos reales para clientes desde 2023. El primero: la web de un estudio de arquitectura.',
    story: 'Del brief al deploy: estructura, contenido y experiencia en Figma; front; back; APIs y bases de datos; responsive y accesibilidad; producción. Trabajo iterativo, con entregables divididos y revisiones progresivas.',
    org: null,
    techs: [
      { slug: 'javascript', name: 'JavaScript' },
      { slug: 'laravel', name: 'Laravel' },
      { slug: 'node', name: 'Node.js' },
      { slug: 'react', name: 'React' },
      { slug: 'typescript', name: 'TypeScript' },
      { slug: 'vue', name: 'Vue 3' },
    ],
  },
  {
    id: 6,
    slug: 'cet-30',
    role: 'Técnico en Programación',
    startedAt: '2017-03-01',
    endedAt: '2023-12-01',
    summary: 'Programación en el CET N.º 30, Río Negro. Título de Técnico en Programación en 2023.',
    story: 'Formación técnica de 7 años en Programación en la Escuela Técnica N.º 30 de Cipolletti, Río Negro. Bases algorítmicas sólidas, estructuras de datos, lógica binaria, redes y metodologías de ingeniería de software.',
    org: { slug: 'cet-30', name: 'CET N.º 30', city: 'Río Negro, AR' },
    techs: [
      { slug: 'javascript', name: 'JavaScript' },
      { slug: 'php', name: 'PHP' },
    ],
  },
]

export const fallbackProjects = [
  {
    id: 1,
    slug: 'la-rucula',
    title: 'La Rúcula Gastrobar',
    year: 2026,
    role: 'Freelance · diseño y desarrollo',
    status: 'LIVE' as const,
    featured: true,
    summary: 'Sitio editorial menu-first para un restaurante frente al mar en Chiclana. Cliente real, en producción.',
    brief: 'La Rúcula necesitaba dejar de ser un PDF escaneado colgado de un QR. El brief real: que la carta se sienta tan cuidada como el plato, y que el dueño pueda editarla sin llamar a nadie.',
    outcome: 'En producción en laruculagastrobar.es. Modo QR optimizado para llegada directa desde la mesa. Multi-locale con preservación del idioma entre rutas. Review UX y accesibilidad automatizadas antes de cada deploy.',
    url: 'https://laruculagastrobar.es/',
    repo: 'https://github.com/MateoGs013/LaRucula',
    metrics: {
      performanceScore: 99,
      accessibilityScore: 100,
      bestPracticesScore: 100,
      seoScore: 100,
      lcp: '0.8s',
      bundleSizeKb: 42,
      localeCount: 2,
    },
    sortOrder: 0,
    publishedAt: '2026-03-17T00:00:00.000Z',
    createdAt: '2026-03-17T00:00:00.000Z',
    updatedAt: '2026-07-20T00:00:00.000Z',
    org: { slug: 'la-rucula-gastrobar', name: 'La Rúcula Gastrobar' },
    techs: [
      { slug: 'gsap', name: 'GSAP' },
      { slug: 'lenis', name: 'Lenis' },
      { slug: 'tailwind', name: 'Tailwind CSS' },
      { slug: 'vite', name: 'Vite' },
      { slug: 'vue', name: 'Vue 3' },
    ],
    links: [
      { label: 'sitio en vivo', url: 'https://laruculagastrobar.es/' },
      { label: 'código fuente', url: 'https://github.com/MateoGs013/LaRucula' },
    ],
    media: [
      {
        id: 1,
        kind: 'IMAGE' as const,
        role: 'COVER' as const,
        src: '/media/projects/la-rucula.jpg',
        alt: 'Home de La Rúcula Gastrobar: titular editorial sobre fotografía de la costa',
        width: 2880,
        height: 1800,
        layer: null,
        order: 0,
        bytes: 218308,
      },
    ],
    steps: [
      { order: 1, title: '01 · encargo', body: 'De un encargo de "página de restaurante" a una experiencia menu-first pensada para el QR en la mesa. La carta tenía que sentirse tan cuidada como el plato.', media: null },
      { order: 2, title: '02 · taller', body: 'Arquitectura menu-first: el sitio se reduce a /, /menu y /menu/:slug. La mayoría del tráfico entra por QR, así que el menú es el producto. El contenido del shell vive en un CMS propio con fallback local: si la API duerme, el sitio no.', media: null },
      { order: 3, title: '03 · pieza', body: 'Home inmersiva de dirección de arte mediterránea: editorial, calma, lejos del layout genérico de restaurante. Motion con significado: reveals de línea, stagger tipográfico y acentos SVG de trazo manual.', media: null },
    ],
    _count: { media: 1, steps: 3 },
  },
  {
    id: 2,
    slug: 'argpiscinas',
    title: 'ARG Piscinas',
    year: 2026,
    role: 'Freelance · front y back a medida',
    status: 'LIVE' as const,
    featured: true,
    summary: 'Web corporativa multi-idioma (ES/EN/DE) con panel admin y blog para una constructora de piscinas en Andalucía. Cliente real, en producción.',
    brief: 'ARG venía de mostrar su trabajo por WhatsApp, foto por foto. El brief: un catálogo serio que muestre obra real, presupuesto en línea, y un panel que el propio cliente pueda operar sin depender de nadie.',
    outcome: 'En producción en argpiscinas.es. Panel autoadministrable: el cliente carga obra sin tocar código. Catálogo tipado de punta a punta con Prisma. Tres idiomas.',
    url: 'https://www.argpiscinas.es/',
    repo: 'https://github.com/MateoGs013/argpiscinas',
    metrics: {
      performanceScore: 98,
      accessibilityScore: 98,
      bestPracticesScore: 100,
      seoScore: 100,
      lcp: '0.9s',
      bundleSizeKb: 58,
      languages: ['ES', 'EN', 'DE'],
    },
    sortOrder: 1,
    publishedAt: '2026-01-28T00:00:00.000Z',
    createdAt: '2026-01-28T00:00:00.000Z',
    updatedAt: '2026-07-20T00:00:00.000Z',
    org: { slug: 'arg-piscinas', name: 'ARG Piscinas' },
    techs: [
      { slug: 'gsap', name: 'GSAP' },
      { slug: 'node', name: 'Node.js' },
      { slug: 'prisma', name: 'Prisma' },
      { slug: 'tailwind', name: 'Tailwind CSS' },
      { slug: 'vite', name: 'Vite' },
      { slug: 'vue', name: 'Vue 3' },
    ],
    links: [
      { label: 'sitio en vivo', url: 'https://www.argpiscinas.es/' },
      { label: 'código fuente', url: 'https://github.com/MateoGs013/argpiscinas' },
    ],
    media: [
      {
        id: 2,
        kind: 'IMAGE' as const,
        role: 'COVER' as const,
        src: '/media/projects/argpiscinas.jpg',
        alt: 'Catálogo de ARG Piscinas con fotografías de obra terminada',
        width: 2880,
        height: 1800,
        layer: null,
        order: 0,
        bytes: 540079,
      },
    ],
    steps: [
      { order: 1, title: '01 · encargo', body: 'Una constructora de piscinas que necesitaba mostrar obra terminada y cotizar sin fricción, en tres idiomas.', media: null },
      { order: 2, title: '02 · taller', body: 'Dos cuerpos sobre una misma API: catálogo público y panel de gestión. Node y Prisma con datos tipados de punta a punta. La obra que carga el cliente es exactamente la que muestra el sitio, sin intermediarios ni deploys de por medio.', media: null },
      { order: 3, title: '03 · pieza', body: 'Front Vue 3 directo y rápido: la obra primero, el argumento después. Catálogo, presupuesto y contacto en el camino más corto posible.', media: null },
    ],
    _count: { media: 1, steps: 3 },
  },
  {
    id: 3,
    slug: 'ynara',
    title: 'Ynara',
    year: 2026,
    role: 'Tesis Da Vinci 2026 · contribuidor principal, 382 commits',
    status: 'WIP' as const,
    featured: true,
    summary: 'Tesis en equipo, preaprobada. Asistente personal de IA adaptativo y on-prem, con memoria cifrada semántica, episódica y procedural sobre Postgres y pgvector.',
    brief: 'Un asistente que corre en tu máquina, habla como vos y se acuerda. Dual LLM (Gemma y Qwen vía Ollama), memoria propia cifrada en tres capas, monorepo FastAPI, Next.js y Expo.',
    outcome: 'Tesis preaprobada con felicitaciones en Da Vinci. 382 commits liderando la arquitectura backend, base de datos vectorial y motor de inferencia local.',
    url: null,
    repo: 'https://github.com/BriarDevv/Ynara',
    metrics: {
      commits: 382,
      vectorDimensions: 1536,
      averageLatencyMs: 48,
      localModels: ['Gemma 2B', 'Qwen 2.5'],
      encryptionLayers: 3,
    },
    sortOrder: 2,
    publishedAt: '2026-05-18T00:00:00.000Z',
    createdAt: '2026-05-18T00:00:00.000Z',
    updatedAt: '2026-06-28T00:00:00.000Z',
    org: { slug: 'escuela-da-vinci', name: 'Escuela Da Vinci' },
    techs: [
      { slug: 'fastapi', name: 'FastAPI' },
      { slug: 'next', name: 'Next.js' },
      { slug: 'postgresql', name: 'PostgreSQL' },
      { slug: 'python', name: 'Python' },
      { slug: 'react', name: 'React' },
      { slug: 'typescript', name: 'TypeScript' },
    ],
    links: [{ label: 'repositorio tesis', url: 'https://github.com/BriarDevv/Ynara' }],
    media: [
      {
        id: 3,
        kind: 'IMAGE' as const,
        role: 'COVER' as const,
        src: '/media/projects/ynara-mtucqc2j.png',
        alt: 'Ynara asistente de IA adaptativo on-premise',
        width: 1280,
        height: 720,
        layer: null,
        order: 0,
        bytes: 394847,
      },
    ],
    steps: [
      { order: 1, title: '01 · hipótesis', body: 'Los asistentes en la nube sacrifican privacidad y contexto local. La hipótesis: un modelo on-prem con memoria vectorial puede ser más rápido, privado y natural.', media: null },
      { order: 2, title: '02 · arquitectura', body: 'Monorepo con FastAPI para orquestación de embeddings y llamadas a Ollama; PostgreSQL 17 con pgvector para búsqueda por similitud coseno; Next.js 14 en frontend web y Expo para móvil.', media: null },
      { order: 3, title: '03 · resultado', body: 'Respuestas contextualizadas con menos de 50ms de latencia de consulta interna y almacenamiento local 100% cifrado.', media: null },
    ],
    _count: { media: 1, steps: 3 },
  },
  {
    id: 4,
    slug: 'barberpole',
    title: 'Barberpole',
    year: 2026,
    role: 'Producto propio · diseño y desarrollo',
    status: 'LIVE' as const,
    featured: false,
    summary: 'SaaS de gestión para peluquerías y barberías: turnos, servicios, clientes y caja en un solo lugar.',
    brief: 'El mostrador era el cuello de botella: reservas por teléfono y cuaderno. El sistema saca los turnos del teléfono y los pone en la agenda, del turno a la caja.',
    outcome: 'En producción y validado. MERN completo con auth por roles, agenda del día, precios y duraciones reales de servicio.',
    url: 'https://parcial-2-peluqueria.vercel.app/',
    repo: 'https://github.com/MateoGs013/barberpole',
    metrics: {
      performanceScore: 95,
      accessibilityScore: 96,
      bestPracticesScore: 100,
      seoScore: 95,
      lcp: '1.1s',
      bundleSizeKb: 64,
    },
    sortOrder: 3,
    publishedAt: '2026-02-10T00:00:00.000Z',
    createdAt: '2026-02-10T00:00:00.000Z',
    updatedAt: '2026-06-15T00:00:00.000Z',
    org: null,
    techs: [
      { slug: 'express', name: 'Express' },
      { slug: 'mongodb', name: 'MongoDB' },
      { slug: 'node', name: 'Node.js' },
      { slug: 'react', name: 'React' },
    ],
    links: [
      { label: 'demo en vivo', url: 'https://parcial-2-peluqueria.vercel.app/' },
      { label: 'código fuente', url: 'https://github.com/MateoGs013/barberpole' },
    ],
    media: [
      {
        id: 4,
        kind: 'IMAGE' as const,
        role: 'COVER' as const,
        src: '/media/projects/barberpole.png',
        alt: 'Agenda del día de barberpole con turnos y servicios',
        width: 2880,
        height: 1800,
        layer: null,
        order: 0,
        bytes: 144234,
      },
    ],
    steps: [
      { order: 1, title: '01 · problema', body: 'El mostrador era el cuello de botella. Reservas por teléfono, cuaderno y memoria.', media: null },
      { order: 2, title: '02 · sistema', body: 'MERN completo: turnos, servicios, clientes y caja en un solo lugar. Auth por roles, agenda del día, precios y duraciones reales.', media: null },
      { order: 3, title: '03 · identidad', body: 'Identidad de barbería de barrio inspirada en el barber pole: neo-brutalista, directa, sin adornos.', media: null },
    ],
    _count: { media: 1, steps: 3 },
  },
  {
    id: 5,
    slug: 'ynara-web',
    title: 'Ynara Web',
    year: 2026,
    role: 'Landing inmersiva · diseño y desarrollo',
    status: 'WIP' as const,
    featured: false,
    summary: 'Landing inmersiva WebGL para Ynara: una forma de luz que muta y reacciona al scroll. Puerta de entrada pública a la tesis.',
    brief: 'Una experiencia espacial que no se navega: se recorre. La narrativa visual se dibuja primero; los shaders entran al servicio de la atmósfera.',
    outcome: 'Shader procedural reactivo a la velocidad de scroll con fallback elegante para dispositivos de baja potencia.',
    url: null,
    repo: 'https://github.com/MateoGs013/Ynara-Web',
    metrics: { fpsTarget: 60, drawCalls: 4, bundleSizeKb: 78 },
    sortOrder: 4,
    publishedAt: '2026-04-01T00:00:00.000Z',
    createdAt: '2026-04-01T00:00:00.000Z',
    updatedAt: '2026-05-15T00:00:00.000Z',
    org: null,
    techs: [
      { slug: 'gsap', name: 'GSAP' },
      { slug: 'lenis', name: 'Lenis' },
      { slug: 'next', name: 'Next.js' },
      { slug: 'react', name: 'React' },
      { slug: 'tailwind', name: 'Tailwind CSS' },
      { slug: 'three', name: 'Three.js' },
      { slug: 'typescript', name: 'TypeScript' },
    ],
    links: [{ label: 'código fuente', url: 'https://github.com/MateoGs013/Ynara-Web' }],
    media: [],
    steps: [
      { order: 1, title: '01 · concepto', body: 'Traducir la inteligencia artificial adaptativa a una entidad lumínica tridimensional.', media: null },
      { order: 2, title: '02 · shaders', body: 'Vertex y fragment shaders personalizados en GLSL sobre Three.js orquestados con GSAP ScrollTrigger.', media: null },
    ],
    _count: { media: 0, steps: 2 },
  },
  {
    id: 6,
    slug: 'eros',
    title: 'Eros',
    year: 2026,
    role: 'Producto propio · diseño y desarrollo',
    status: 'WIP' as const,
    featured: false,
    summary: 'Director creativo autónomo asistido por IA con su base de conocimiento en un vault de Obsidian.',
    brief: 'Automatizar la curaduría estética, la síntesis de referencias de diseño y la formulación de prompts creativos estructurados.',
    outcome: 'Prototipo funcional en CLI y micro-servidor local de enriquecimiento semántico.',
    url: null,
    repo: 'https://github.com/MateoGs013/eros',
    metrics: { vaultNotesParsed: 1420, graphNodes: 850 },
    sortOrder: 5,
    publishedAt: '2026-05-01T00:00:00.000Z',
    createdAt: '2026-05-01T00:00:00.000Z',
    updatedAt: '2026-06-01T00:00:00.000Z',
    org: null,
    techs: [
      { slug: 'gsap', name: 'GSAP' },
      { slug: 'lenis', name: 'Lenis' },
      { slug: 'python', name: 'Python' },
      { slug: 'vue', name: 'Vue 3' },
    ],
    links: [{ label: 'código fuente', url: 'https://github.com/MateoGs013/eros' }],
    media: [],
    steps: [
      { order: 1, title: '01 · concepción', body: 'Conectar un vault personal de markdown con agentes LLM para análisis de patrones visuales.', media: null },
    ],
    _count: { media: 0, steps: 1 },
  },
]

export const fallbackStack = [
  { id: 1, slug: 'javascript', name: 'JavaScript', category: 'LANGUAGE' as const, since: 2022, note: 'Fundamento del desarrollo web moderno, estándares ECMAScript y manipulación del DOM nativo.', color: '#f7df1e', _count: { projects: 0, experiences: 2 } },
  { id: 2, slug: 'angular', name: 'Angular', category: 'FRAMEWORK' as const, since: 2022, note: 'Arquitectura corporativa basada en RxJS y Dependency Injection.', color: '#dd0031', _count: { projects: 0, experiences: 0 } },
  { id: 3, slug: 'typescript', name: 'TypeScript', category: 'LANGUAGE' as const, since: 2023, note: 'Estándar obligatorio en cliente y servidor: si no está tipado en compilación, no llega a producción.', color: '#3178c6', _count: { projects: 2, experiences: 2 } },
  { id: 4, slug: 'node', name: 'Node.js', category: 'BACKEND' as const, since: 2024, note: 'Runtime de alto rendimiento para APIs REST livianas, pipelines de middleware y servidores de eventos.', color: '#339933', _count: { projects: 2, experiences: 2 } },
  { id: 5, slug: 'express', name: 'Express', category: 'BACKEND' as const, since: 2024, note: 'Minimalismo y control total sobre el ciclo de vida HTTP, routing y autenticación.', color: '#000000', _count: { projects: 1, experiences: 0 } },
  { id: 6, slug: 'firebase', name: 'Firebase', category: 'DATA' as const, since: 2024, note: 'Plataforma BaaS para base de datos NoSQL reactiva y autenticación social rápida.', color: '#ffca28', _count: { projects: 0, experiences: 0 } },
  { id: 7, slug: 'php', name: 'PHP', category: 'LANGUAGE' as const, since: 2025, note: 'Lenguaje backend tradicional utilizado en integraciones y módulos transaccionales de clientes.', color: '#777bb4', _count: { projects: 0, experiences: 2 } },
  { id: 8, slug: 'vue', name: 'Vue 3', category: 'FRAMEWORK' as const, since: 2025, note: 'Elegido por reactividad quirúrgica, Composition API limpia y tipado estricto sin sobrecarga de boilerplate.', color: '#42b883', _count: { projects: 3, experiences: 4 } },
  { id: 9, slug: 'vite', name: 'Vite', category: 'TOOLING' as const, since: 2025, note: 'Tooling ultra veloz basado en Rollup y esbuild para HMR instantáneo en desarrollo.', color: '#646cff', _count: { projects: 2, experiences: 0 } },
  { id: 10, slug: 'python', name: 'Python', category: 'LANGUAGE' as const, since: 2026, note: 'Lenguaje predilecto para ingeniería de datos, embeddings vectoriales y orquestación de LLMs.', color: '#3776ab', _count: { projects: 2, experiences: 1 } },
  { id: 11, slug: 'react', name: 'React', category: 'FRAMEWORK' as const, since: 2026, note: 'Ecosistema masivo, React Server Components y rendering híbrido adoptado en la tesis Ynara.', color: '#61dafb', _count: { projects: 3, experiences: 2 } },
  { id: 12, slug: 'next', name: 'Next.js', category: 'FRAMEWORK' as const, since: 2026, note: 'Framework full-stack de React con optimización de assets, routing por sistema de archivos y SSR.', color: '#000000', _count: { projects: 2, experiences: 1 } },
  { id: 13, slug: 'gsap', name: 'GSAP', category: 'MOTION' as const, since: 2026, note: 'Orquestación temporal determinista para interfaces de alta precisión y micro-interacciones espaciales.', color: '#88ce02', _count: { projects: 4, experiences: 2 } },
  { id: 14, slug: 'lenis', name: 'Lenis', category: 'MOTION' as const, since: 2026, note: 'Scroll inercial normalizado multiplataforma sin romper el comportamiento nativo del navegador.', color: '#111111', _count: { projects: 3, experiences: 1 } },
  { id: 15, slug: 'three', name: 'Three.js', category: 'GRAPHICS' as const, since: 2026, note: 'WebGL y shaders GLSL para experiencias inmersivas 3D cuando el DOM no alcanza.', color: '#000000', _count: { projects: 1, experiences: 0 } },
  { id: 16, slug: 'laravel', name: 'Laravel', category: 'BACKEND' as const, since: 2026, note: 'Monolito robusto con Eloquent ORM, autenticación por sesión y colas de trabajo para plataformas transaccionales.', color: '#ff2d20', _count: { projects: 0, experiences: 2 } },
  { id: 17, slug: 'fastapi', name: 'FastAPI', category: 'BACKEND' as const, since: 2026, note: 'Core de inferencia y procesamiento de IA/NLP con tipado Pydantic y latencia mínima.', color: '#009688', _count: { projects: 1, experiences: 2 } },
  { id: 18, slug: 'prisma', name: 'Prisma', category: 'DATA' as const, since: 2026, note: 'ORM tipado de punta a punta: genera tipos TypeScript exactos directamente desde el esquema SQL.', color: '#2d3748', _count: { projects: 1, experiences: 1 } },
  { id: 19, slug: 'postgresql', name: 'PostgreSQL', category: 'DATA' as const, since: 2026, note: 'Persistencia relacional ACID, esquemas declarativos e índices vectoriales con pgvector.', color: '#4169e1', _count: { projects: 1, experiences: 2 } },
  { id: 20, slug: 'mongodb', name: 'MongoDB', category: 'DATA' as const, since: 2026, note: 'Base NoSQL orientada a documentos para prototipado ágil y esquemas dinámicos en Barberpole.', color: '#47a248', _count: { projects: 1, experiences: 1 } },
  { id: 21, slug: 'supabase', name: 'Supabase', category: 'DATA' as const, since: 2026, note: 'Backend-as-a-Service con Postgres en tiempo real, Row Level Security y storage S3.', color: '#3ecf8e', _count: { projects: 0, experiences: 0 } },
  { id: 22, slug: 'tailwind', name: 'Tailwind CSS', category: 'TOOLING' as const, since: 2026, note: 'Sistema de diseño componible y utilitario con purga agresiva para bundles ultra ligeros.', color: '#06b6d4', _count: { projects: 3, experiences: 2 } },
]
